In [8]:
import torch
from torch import nn, optim
import torch.nn.functional as F
import numpy as np
import torch.optim as optim

import os, sys
from torch.utils.tensorboard import SummaryWriter
import torchvision
import torchvision.transforms as transforms

writer = SummaryWriter("runs/tensor_visualization_test_1")

PARENT_DIR = os.path.abspath("__file__" + "/../../")
sys.path.insert(0, PARENT_DIR)
CUR_DIR = os.path.abspath("__file__" + "/..")
sys.path.insert(0, CUR_DIR)

#from rcognita.objectives import RunningObjective

#running_objective = RunningObjective(running_obj_model="quadratic")





In [9]:
class ModelNN(nn.Module):
    def __init__(self, dim_observation, dim_action, dim_hidden=5, weights=None):
        super().__init__()

        self.model_name = "NN"
        self.fc1 = nn.Linear(dim_observation + dim_action, dim_hidden, bias=False)
        self.relu1 = nn.LeakyReLU()
        self.fc2 = nn.Linear(dim_hidden, dim_observation, bias=False)

        if weights is not None:
            self.load_state_dict(weights)

        self.double()

    def forward(self, x, weights=None):
        # print("x type", type(x))

        x = x.double()

        x = self.fc1(x)
        x = self.relu1(x)
        x = self.fc2(x)
        x = torch.linalg.vector_norm(x)

        return x  # .detach().numpy()

    def __call__(self, observation, action, weights=None):

        concat = np.concatenate((observation, action))
        to_torch = torch.tensor(concat)

        if not weights is None:
            state_dict = self.weights2dict(weights)
            self.load_state_dict(state_dict)

        return self.forward(to_torch)


model = ModelNN(3, 2)

input_tensor_1 = torch.randn(1, 5)
input_tensor_2 = torch.randn(1, 5)

optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.8)

print([x for x in model.parameters()])

loss = model.forward(input_tensor_1) - model.forward(input_tensor_2)


loss.backward()

for _ in range(100):
    optimizer.step()

print([x for x in model.parameters()])
print(model.parameters)

[Parameter containing:
tensor([[-0.1858,  0.1895, -0.4341,  0.3522, -0.1956],
        [-0.0250,  0.4026, -0.0163,  0.2166,  0.2568],
        [-0.0382, -0.2872, -0.1190, -0.3581, -0.0155],
        [ 0.0593, -0.1189,  0.1174, -0.1454, -0.3595],
        [-0.3356,  0.0907, -0.3424,  0.3077, -0.0307]], dtype=torch.float64,
       requires_grad=True), Parameter containing:
tensor([[ 0.1815, -0.3175, -0.2123,  0.1307,  0.3886],
        [ 0.1496,  0.0634,  0.1710, -0.4094,  0.0477],
        [ 0.0630,  0.2838, -0.3854,  0.3038, -0.4136]], dtype=torch.float64,
       requires_grad=True)]
[Parameter containing:
tensor([[-2.0996e-01,  1.9319e-01, -4.2288e-01,  3.5043e-01, -1.9707e-01],
        [-3.9810e-02,  4.0499e-01, -9.4656e-03,  2.1576e-01,  2.5591e-01],
        [ 9.5464e+00, -2.0030e+00, -4.6112e+00, -2.1345e-01,  6.6961e-01],
        [-8.1429e+00,  1.4401e+00,  3.9779e+00, -8.3509e-02, -9.8167e-01],
        [-3.0118e-01,  8.4536e-02, -3.5851e-01,  3.0830e-01, -2.8303e-02]],
       dtype=tor

In [11]:
!tensorboard dev upload --logdir 'runs'

TensorFlow installation not found - running with reduced feature set.

***** TensorBoard Uploader *****

This will upload your TensorBoard logs to https://tensorboard.dev/ from
the following directory:

runs

This TensorBoard will be visible to everyone. Do not upload sensitive
data.

Your use of this service is subject to Google's Terms of Service
<https://policies.google.com/terms> and Privacy Policy
<https://policies.google.com/privacy>, and TensorBoard.dev's Terms of Service
<https://tensorboard.dev/policy/terms/>.

This notice will not be shown again while you are logged into the uploader.
To log out, run `tensorboard dev auth revoke`.

Continue? (yes/NO) ^C
Traceback (most recent call last):
  File "/home/odinmaniac/anaconda3/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/home/odinmaniac/anaconda3/lib/python3.9/site-packages/tensorboard/main.py", line 46, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/home/odinmania

In [18]:
writer.add_graph(model, input_to_model=[torch.randn(3, 1), torch.randn(2, 1)], verbose=False)

mat1 and mat2 shapes cannot be multiplied (5x1 and 5x5)
Error occurs, No graph saved


/tmp/ipykernel_909791/326118733.py:30: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  to_torch = torch.tensor(concat)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x1 and 5x5)

In [33]:
from enum import IntEnum

class OrderedEnum(Enum):
    def __ge__(self, other):
        if self.__class__ is other.__class__:
            return self.value >= other.value
        return NotImplemented
    def __gt__(self, other):
        if self.__class__ is other.__class__:
            return self.value > other.value
        return NotImplemented
    def __le__(self, other):
        if self.__class__ is other.__class__:
            return self.value <= other.value
        return NotImplemented
    def __lt__(self, other):
        if self.__class__ is other.__class__:
            return self.value < other.value
        return NotImplemented

class RCType(IntEnum):
    TORCH = 3
    CASADI = 2
    NUMPY = 1


TORCH = RCType.TORCH
CASADI = RCType.CASADI
NUMPY = RCType.NUMPY


In [34]:
print(max(TORCH, 1))

RCType.TORCH


In [31]:
max(1,2,3)

3